# version: '3.8'

services:
  # MongoDB Primary Node
  mongo1:
    image: mongo:7.0
    container_name: mongo1
    hostname: mongo1
    restart: always
    command: >
     bash -c "
       mkdir -p /etc/secrets &&
       mongod --replSet rs0 --bind_ip_all --port 27017 --auth --keyFile /etc/secrets/mongodb-keyfile
     "
    ports:
      - "27017:27017"
    volumes:
      - ./keyfile/mongodb-keyfile:/etc/secrets/mongodb-keyfile:ro
      - mongo1_data:/data/db
      - mongo1_config:/data/configdb
      - ./scripts:/scripts
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_DATABASE}
    networks:
      - mongo-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3
  
  # MongoDB Secondary Node 1
  mongo2:
    image: mongo:7.0
    container_name: mongo2
    hostname: mongo2
    restart: always
    command: >
     bash -c "
       mkdir -p /etc/secrets &&
       mongod --replSet rs0 --bind_ip_all --port 27017 --auth --keyFile /etc/secrets/mongodb-keyfile
     "
    ports:
      - "27018:27017"
    volumes:
      - ./keyfile/mongodb-keyfile:/etc/secrets/mongodb-keyfile:ro
      - mongo2_data:/data/db
      - mongo2_config:/data/configdb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
    networks:
      - mongo-network
    depends_on:
      - mongo1

  # MongoDB Secondary Node 2
  mongo3:
    image: mongo:7.0
    container_name: mongo3
    hostname: mongo3
    restart: always
    command: >
     bash -c "
       mkdir -p /etc/secrets &&
       mongod --replSet rs0 --bind_ip_all --port 27017 --auth --keyFile /etc/secrets/mongodb-keyfile
     "
    ports:
      - "27019:27017"
    volumes:
      - ./keyfile/mongodb-keyfile:/etc/secrets/mongodb-keyfile:ro
      - mongo3_data:/data/db
      - mongo3_config:/data/configdb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
    networks:
      - mongo-network
    depends_on:
      - mongo1

  # MongoDB Express for Web UI (Optional)
  mongo-express:
    image: mongo-express:1.0.0
    container_name: mongo-express
    restart: always
    ports:
      - "${MONGO_EXPRESS_PORT:-8081}:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_ROOT_USERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_ROOT_PASSWORD}
      - ME_CONFIG_MONGODB_URL=mongodb://${MONGO_ROOT_USERNAME}:${MONGO_ROOT_PASSWORD}@mongo1:27017,mongo2:27017,mongo3:27017/?replicaSet=rs0
      - ME_CONFIG_BASICAUTH_USERNAME=${MONGO_EXPRESS_USERNAME}
      - ME_CONFIG_BASICAUTH_PASSWORD=${MONGO_EXPRESS_PASSWORD}
    networks:
      - mongo-network
    depends_on:
      - mongo1
      - mongo2
      - mongo3

# Định nghĩa volumes để lưu trữ dữ liệu
volumes:
  mongo1_data:
    driver: local
  mongo1_config:
    driver: local
  mongo2_data:
    driver: local
  mongo2_config:
    driver: local
  mongo3_data:
    driver: local
  mongo3_config:
    driver: local

# Định nghĩa network
networks:
  mongo-network:
    driver: bridge