version: '3.8'

services:
  # MongoDB Primary Node
  mongo1:
    image: mongo:7.0
    container_name: mongo1
    hostname: mongo1
    restart: unless-stopped
    command: mongod --replSet rs0 --bind_ip_all --port 27017
    ports:
      - "27017:27017"
    volumes:
      - mongo1_data:/data/db
      - mongo1_config:/data/configdb
      - ./scripts:/scripts
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password123
    networks:
      - mongo-network

  # MongoDB Secondary Node 1
  mongo2:
    image: mongo:7.0
    container_name: mongo2
    hostname: mongo2
    restart: unless-stopped
    command: mongod --replSet rs0 --bind_ip_all --port 27017
    ports:
      - "27018:27017"
    volumes:
      - mongo2_data:/data/db
      - mongo2_config:/data/configdb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password123
    networks:
      - mongo-network
    depends_on:
      - mongo1

  # MongoDB Secondary Node 2
  mongo3:
    image: mongo:7.0
    container_name: mongo3
    hostname: mongo3
    restart: unless-stopped
    command: mongod --replSet rs0 --bind_ip_all --port 27017
    ports:
      - "27019:27017"
    volumes:
      - mongo3_data:/data/db
      - mongo3_config:/data/configdb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password123
    networks:
      - mongo-network
    depends_on:
      - mongo1

  # MongoDB Express for Web UI (Optional)
  mongo-express:
    image: mongo-express:1.0.0
    container_name: mongo-express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password123
      - ME_CONFIG_MONGODB_SERVER=mongo1
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=webpass123
    networks:
      - mongo-network
    depends_on:
      - mongo1

# Định nghĩa volumes để lưu trữ dữ liệu
volumes:
  mongo1_data:
    driver: local
  mongo1_config:
    driver: local
  mongo2_data:
    driver: local
  mongo2_config:
    driver: local
  mongo3_data:
    driver: local
  mongo3_config:
    driver: local

# Định nghĩa network
networks:
  mongo-network:
    driver: bridge